server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?useSSL=false&serverTimezone=UTC
    username: capstone
    password: MyCapstonePassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
    kafka: ERROR

# Kafka topic names
jfc:
  topics:
    ingestion: "job-ingestion"
    status: "common-job-status"
    # For demonstration, assume 3 tools:
    jobA: "JobA-destination"
    jobB: "JobB-destination"
    jobC: "JobC-destination"